name: nextflow-pipeline-analytics
channels:
  - conda-forge
  - snowflake
dependencies:
  - python=3.11.*
  - streamlit>=1.28.0
  - pandas>=2.0.0
  - numpy>=1.24.0
  - plotly>=5.15.0
  - altair>=5.0.0
  - pip
  - pip:
    - snowflake-connector-python>=3.0.0
    - snowflake-snowpark-python>=1.11.0
